apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goofydo

resources:
  - namespace.yaml
  - postgres.yaml
  - keycloak.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - db-bootstrap-job.yaml
  - serviceaccounts.yaml
  - network-policy.yaml

configMapGenerator:

  - name: keycloak-realm-import
    files:
      - todo-realm.json=files/keycloak/todo-realm.json

generatorOptions:
  disableNameSuffixHash: true