apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: goofydo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: goofydo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-sa
  namespace: goofydo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: goofydo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-bootstrap-sa
  namespace: goofydo
automountServiceAccountToken: false